# Generated by Django 4.0.2 on 2022-03-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.land')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.race')),
            ],
        ),
    ]
